CREATE TABLE IF NOT EXISTS ORDERS(
ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
CUSTOMER_ID INT REFERENCES CUSTOMER(CUSTOMER_ID),
ORDER_DATE DATE,
ITEM_NAME VARCHAR(15)
);


CREATE TABLE IF NOT EXISTS CUSTOMER(
CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
CUSTOMER_NAME VARCHAR(15),
EMAIL VARCHAR(20),
ADDRESS VARCHAR(15)
);

SELECT ORDER_ID,C.CUSTOMER_ID,CUSTOMER_NAME,ITEM_NAME,ORDER_DATE
FROM CUSTOMER C INNER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID ORDER BY CUSTOMER_ID;

SELECT ORDER_ID,C.CUSTOMER_ID,CUSTOMER_NAME,ITEM_NAME,ORDER_DATE 
FROM CUSTOMER C INNER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID WHERE O.ORDER_DATE BETWEEN '2014-05-15' AND '2016-09-20' ORDER BY ORDER_DATE ;

SELECT ORDER_ID,C.CUSTOMER_ID,CUSTOMER_NAME,ITEM_NAME 
FROM CUSTOMER C LEFT OUTER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID;

SELECT ORDER_ID,C.CUSTOMER_ID,CUSTOMER_NAME,ITEM_NAME 
FROM CUSTOMER C RIGHT OUTER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID;

SELECT ORDER_ID,C.CUSTOMER_ID,CUSTOMER_NAME,ITEM_NAME
FROM CUSTOMER C LEFT OUTER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
UNION
SELECT ORDER_ID,C.CUSTOMER_ID,CUSTOMER_NAME,ITEM_NAME 
FROM CUSTOMER C RIGHT OUTER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID;


SELECT ORDER_ID,C.CUSTOMER_ID,CUSTOMER_NAME,ITEM_NAME
FROM CUSTOMER C INNER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID WHERE  O.ITEM_NAME='SHIRT';

SELECT ORDER_ID,C.CUSTOMER_ID,CUSTOMER_NAME,ITEM_NAME
FROM CUSTOMER C LEFT OUTER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID WHERE  O.ITEM_NAME='SHIRT';

SELECT ORDER_ID,C.CUSTOMER_ID,CUSTOMER_NAME,ITEM_NAME
FROM CUSTOMER C INNER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
WHERE O.ITEM_NAME LIKE '_____';

SELECT ORDER_ID ,C.CUSTOMER_ID,CUSTOMER_NAME,ITEM_NAME
FROM CUSTOMER C LEFT JOIN  ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
WHERE O.CUSTOMER_ID IS NULL;

SELECT ORDER_ID ,C.CUSTOMER_ID,CUSTOMER_NAME,ITEM_NAME
FROM CUSTOMER C RIGHT JOIN  ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;


SELECT ORDER_ID ,C.CUSTOMER_ID,CUSTOMER_NAME,ITEM_NAME
FROM CUSTOMER C LEFT JOIN  ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
WHERE O.CUSTOMER_ID IS NULL
UNION
SELECT ORDER_ID ,C.CUSTOMER_ID,CUSTOMER_NAME,ITEM_NAME
FROM CUSTOMER C RIGHT JOIN  ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;

SELECT C.CUSTOMER_ID,CUSTOMER_NAME,COUNT(ORDER_ID) AS ITEMS_PURCHASED 
FROM CUSTOMER C INNER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
WHERE C.CUSTOMER_NAME='DAN CHENDRA';


CREATE TABLE IF NOT EXISTS emp(
empno int(4) not null primary key,
ename varchar(50) not null,
job varchar(50) not null,
mgr int(4),
hiredate date,
sal decimal(10,2),
comm decimal(10,2),
deptno int(2) not null);

/*--------SELF JOIN--------*/
SELECT E.EMPNO,E.ENAME AS EMPLOYEE_NAME ,M.ENAME AS MANAGER_NAME FROM
emp E INNER JOIN emp M 
ON E.MGR=M.EMPNO;
