CREATE TABLE IF NOT EXISTS STORE_INFORMATION(
STORE_NAME VARCHAR(20),
SALES_INFO INTEGER(10));

ALTER TABLE STORE_INFORMATION ADD (YEAR DATE);

ALTER TABLE STORE_INFORMATION ADD(ID NUMERIC(5) PRIMARY KEY);

ALTER TABLE STORE_INFORMATION MODIFY SALES_INFO NUMERIC(10);

ALTER TABLE STORE_INFORMATION DROP COLUMN ID;

ALTER TABLE STORE_INFORMATION ADD COLUMN ID INT AUTO_INCREMENT  PRIMARY KEY;

SHOW TABLES;

DESCRIBE STORE_INFORMATION;

INSERT INTO STORE_INFORMATION (STORE_NAME,SALES_INFO,YEAR) values('Los Angeles',120 ,'2012-01-01');

SELECT * FROM STORE_INFORMATION;

SELECT * FROM STORE_INFORMATION WHERE STORE_NAME LIKE '%Los%';

SELECT * FROM STORE_INFORMATION WHERE STORE_NAME LIKE '_______';

SELECT * FROM STORE_INFORMATION WHERE ID IN (1,2,3);

SELECT * FROM STORE_INFORMATION WHERE ID IN (2,4,6,8);

SELECT * FROM STORE_INFORMATION WHERE SALES_INFO IN (18,170);

SELECT * FROM STORE_INFORMATION WHERE YEAR BETWEEN '2013-01-01' AND '2016-01-01';

SELECT * FROM STORE_INFORMATION WHERE ID BETWEEN 2 AND 8;

SELECT MAX(ID) FROM STORE_INFORMATION;

SELECT DISTINCT(STORE_NAME) FROM STORE_INFORMATION;

SELECT SUM(ID) FROM STORE_INFORMATION;

SELECT * FROM STORE_INFORMATION WHERE SALES_INFO=(SELECT MAX(SALES_INFO) FROM STORE_INFORMATION); 

SELECT SALES_INFO,MAX(SALES_INFO) FROM STORE_INFORMATION GROUP BY SALES_INFO HAVING  MAX(SALES_INFO)=100;

SELECT STORE_NAME ,COUNT(*) FROM STORE_INFORMATION GROUP BY STORE_NAME;

SELECT SALES_INFO,COUNT(*) FROM STORE_INFORMATION GROUP BY SALES_INFO;

SELECT YEAR,COUNT(*) FROM STORE_INFORMATION GROUP BY YEAR;

SELECT * FROM STORE_INFORMATION ORDER BY SALES_INFO;

SELECT * FROM STORE_INFORMATION ORDER BY SALES_INFO DESC;

SELECT STORE_NAME,SALES_INFO,MIN(SALES_INFO) FROM STORE_INFORMATION GROUP BY STORE_NAME;

SELECT ID,STORE_NAME,SALES_INFO,YEAR  FROM STORE_INFORMATION GROUP BY STORE_NAME HAVING  COUNT(STORE_NAME)>=1;