DELIMITER $$

CREATE DEFINER=`athora0`@`%` PROCEDURE `GET_WORK_ORDER`(IN PARAM INT)
BEGIN
SELECT S.SLIP_ID,BOAT_NAME,M.MARINA_NUM,MARINA_NAME,OWNER_NAME,
MOBILE,STREET,CITY,STATE,L.ZIP_CODE,O.OWNER_NUM,SE.SERVICE_ID,CA.CATEGORY_NUM,
CATEGORY_DESC,JOB_DESC,EST_HRS,NEXT_SRVC_DATE 
FROM SLIP_DETAILS S INNER JOIN SERVICES SE
INNER JOIN MARINA_DETAILS M 
INNER JOIN LOCATION L
INNER JOIN OWNER_DETAILS O
INNER JOIN CATEGORIES CA
ON
S.SLIP_ID=SE.SLIP_ID AND
S.MARINA_NUM=M.MARINA_NUM AND
SE.CATEGORY_NUM=CA.CATEGORY_NUM AND
O.ZIP_CODE=L.ZIP_CODE AND
S.OWNER_NUM=O.OWNER_NUM WHERE O.OWNER_NUM=PARAM;
END
